FROM node:22-alpine
WORKDIR /app

RUN apk update && apk upgrade --no-cache
RUN npm i -g pnpm

COPY package.json .
COPY pnpm-lock.yaml .

RUN pnpm i --frozen-lockfile --prod

COPY . .

RUN pnpm build

ENV NODE_ENV=production

ENTRYPOINT pnpm start:prod
