FROM node:22-alpine
WORKDIR /app

RUN apk update
RUN apk upgrade --no-cache
RUN apk add curl
RUN npm i -g -f pnpm

COPY package.json .
COPY pnpm-lock.yaml .

RUN pnpm i --frozen-lockfile

COPY . .

ENV NODE_ENV=development
ENTRYPOINT pnpm start:dev
