FROM node:22-alpine
WORKDIR /app

RUN apk update && apk upgrade --no-cache
RUN npm i -g pnpm

COPY package.json .
COPY pnpm-lock.yaml .

RUN pnpm i --frozen-lockfile

COPY . .

ENV NODE_ENV=development
ENTRYPOINT pnpm start:dev
